# Generated by Django 3.1.5 on 2021-01-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Car Brand')),
                ('license_plate', models.CharField(max_length=255, verbose_name='License Plate')),
                ('car_type', models.PositiveSmallIntegerField(choices=[(1, 'Suv'), (2, 'Sedane'), (3, 'Hatchback'), (4, 'Other')], default=4)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
            ],
            options={
                'verbose_name': 'Car Wash',
                'verbose_name_plural': 'Car Washes',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='carwash.location')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='carwash.supplier')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='carwash.carwash')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.AddField(
            model_name='carwash',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='carwash.location'),
        ),
        migrations.AddField(
            model_name='carwash',
            name='supplier',
            field=models.ManyToManyField(related_name='company', to='carwash.Supplier'),
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=255, verbose_name='Booth Number')),
                ('occupied', models.BooleanField(default=False, verbose_name='Occupied')),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booth', to='carwash.car')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth', to='carwash.carwash')),
                ('washer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth', to='carwash.employee')),
            ],
            options={
                'verbose_name': 'Booth',
                'verbose_name_plural': 'Booths',
                'unique_together': {('company', 'booth_number')},
            },
        ),
    ]
