# Generated by Django 3.1.5 on 2021-01-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='booth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='carwash.booth'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='company', to='carwash.location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='carwash.carwash'),
        ),
    ]
