# Generated by Django 3.1.5 on 2021-01-23 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_auto_20210123_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booth',
            unique_together={('company_id', 'booth_number')},
        ),
    ]
