# Generated by Django 3.1.5 on 2021-01-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_auto_20210123_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='booth',
        ),
    ]
