# Generated by Django 3.1.5 on 2021-01-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_remove_car_booth'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booth', to='carwash.car'),
        ),
    ]
