# Generated by Django 3.1.5 on 2021-01-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0006_auto_20210124_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='washer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth', to='carwash.employee'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier', to='carwash.location')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='carwash.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='carwash',
            name='supplier',
            field=models.ManyToManyField(related_name='company', to='carwash.Supplier'),
        ),
    ]
