# Generated by Django 3.1.5 on 2021-01-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Cut'),
        ),
    ]
